---
title: "Cluster comparisons, PH1-5, Z5"
author: "Niamh Errington"
date: "`r format(Sys.time(), '%d %B %Y')`" 
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: false
---

Using zscored data, with values < 5 sd from mean

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

## Running OMADA

```{r, message=FALSE, warning=FALSE}
#load libraries
library(tidyverse)
library(janitor)
library(omada)
library(readr)
library(qwraps2)               
library(kableExtra)
library(ggalluvial)
library(clustree)


#load previously cached chunks
#qwraps2::lazyload_cache_dir(path = "Z5_ClusterComparison_cache/html")
source("../custom_optimalClustering.R")

#load Zscored data
zscored <- read_csv("../../Data/z_TI_noout_5_PH12345.csv") 

#Remove all cols other than numeric miRNAs
miRdata <- zscored %>% select(starts_with("hsa")) %>% as.matrix(.)
rownames(miRdata) <- zscored$SampleID
```


```{r}
# Perform PCA
pca_result <- prcomp(miRdata, scale. = TRUE)

# Extract PC scores
pc_scores <- as.data.frame(pca_result$x) %>% rownames_to_column(var = "SampleID") 

```


```{r}
library(Rtsne)
# Perform t-SNE
tsne_result <- Rtsne(miRdata)

# Extract the two-dimensional embedding
tsne_embedding <- tsne_result$Y
tsne <- cbind(tsne_embedding, zscored) 
```

# Heatmaps

```{r}
library(pheatmap)
library(kernlab)

# Function to perform spectral clustering and plot heatmap
generate_spectral_heatmap <- function(data, row_clusters, col_clusters, title_suffix = "") {
  # Perform spectral clustering on rows
  spectral_rows <- specc(as.matrix(data), centers = row_clusters)
  row_clusters_order <- as.integer(spectral_rows)

  # Perform spectral clustering on columns (transpose the data for clustering columns)
  spectral_cols <- specc(t(as.matrix(data)), centers = col_clusters)
  col_clusters_order <- as.integer(spectral_cols)

  # Reorder the data based on the cluster assignments
  data_ordered <- data[order(row_clusters_order), order(col_clusters_order)]

  # Define the color palette
  my_palette <- colorRampPalette(c("blue", "white", "red"))(100)

  # Plot heatmap with reordered data
  pheatmap(data_ordered, color = my_palette,
           cluster_rows = FALSE, cluster_cols = FALSE, # Spectral clustering already done
           main = paste("miRNA Expression Heatmap -", row_clusters, "Row Clusters,",
                        col_clusters, "Column Clusters", title_suffix))
}

# Example: Generate heatmaps with different number of clusters
cluster_combinations <- list(
  c(3, 3),
  c(4, 4),
  c(5,5),
  c(6,6),
  c(7,7),
  c(8,8),
  c(9,9)
)

# Loop through each cluster combination and generate heatmaps
for (clusters in cluster_combinations) {
  row_k <- clusters[1]
  col_k <- clusters[2]
  generate_spectral_heatmap(miRdata, row_k, col_k)
}

#generate_spectral_heatmap(miRdata, 5,5)

```


# Clustertrees

```{r}
cluster_memberships <- read_csv( "PH12345_25memberships_Z5_allmiR.csv")

colnames(cluster_memberships) <-  sub("\\.memberships", "", colnames(cluster_memberships))

members_long <- cluster_memberships %>% pivot_longer(cols = !c("SampleID"), values_to = "cluster") 
  
members_long$name <- factor(members_long$name, levels = c("k2", "k3", "k4", "k5", "k6", "k7", "k8", "k9", "k10", "k11", "k12", "k13", "k14", "k15", "k16", "17", "k18", "k19", "k20", "k21", "k22", "k23", "k24", "k25"))

members_long$cluster <- factor(members_long$cluster)


ggplot(members_long,
       aes(x = name, stratum = cluster, alluvium = SampleID,
           fill = cluster, label = cluster)) +
  geom_flow(stat = "alluvium", lode.guidance = "frontback") +
  geom_stratum() +
  theme(legend.position = "bottom") + labs(x = "Max cluster available", y = "n" ,title = "Cluster memberships") + theme_minimal()

members_long %>% filter(name %in% c("k2", "k3", "k4", "k5","k6", "k7", "k8", "k9", "k10")) %>% ggplot( aes(x = name, stratum = cluster, alluvium = SampleID,
           fill = cluster, label = cluster)) +
  geom_flow(stat = "alluvium", lode.guidance = "frontback") +
  geom_stratum() +
  theme(legend.position = "bottom") + labs(x = "Max cluster available", y = "n" ,title = "Cluster memberships, k2-10") + theme_minimal()


```

```{r, eval = F}
clustree(cluster_memberships, prefix = "k")

cluster_memberships %>% select("k2", "k3", "k4", "k5", "k6", "k7", "k8", "k9", "k10") %>% clustree(., prefix = "k")

cluster_memberships %>% select("k10", "k11","k12", "k13", "k14", "k15", "k16", "k17", "k18", "k19", "k20") %>% clustree(., prefix = "k")

cluster_memberships %>% select("k19", "k20", "k21", "k22", "k23", "k24", "k25") %>% clustree(., prefix = "k")

```


# TSNE

```{r}
# Extract the two-dimensional embedding
tsne_embedding <- tsne_result$Y
tsne <- cbind(tsne_embedding, zscored) 

tsne <- left_join(tsne, cluster_memberships, by = "SampleID")

tsne %>% ggplot(aes(x = `1`, y = `2`, color = as.factor(sex))) + geom_point()  +
  ggtitle("t-SNE Plot, sex") + theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "grey"), axis.line = element_line(colour = "grey"), strip.text = element_text(size = 16)) +  guides(color=guide_legend(title=NULL))  + scale_color_manual(values = c("lightpink", "deeppink"))

tsne %>% ggplot(aes(x = `1`, y = `2`, color = as.factor(site))) + geom_point()  +
  ggtitle("t-SNE Plot, site") + theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "grey"), axis.line = element_line(colour = "grey"), strip.text = element_text(size = 16)) +  guides(color=guide_legend(title=NULL))  + scale_color_manual(values = c("lightpink", "deeppink", "midnightblue"))

tsne %>% ggplot(aes(x = `1`, y = `2`, color = as.factor(dana1))) + geom_point()  +
  ggtitle("t-SNE Plot, DANA") + theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "grey"), axis.line = element_line(colour = "grey"), strip.text = element_text(size = 16)) +  guides(color=guide_legend(title=NULL))  + scale_color_manual(values = c("lightpink", "deeppink", "midnightblue", "black", "lightgreen"))

tsne %>% ggplot(aes(x = `1`, y = `2`, color = as.factor(k5))) + geom_point()  +   ggtitle("t-SNE Plot, k=5") + theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "grey"), axis.line = element_line(colour = "grey"), strip.text = element_text(size = 16)) +  guides(color=guide_legend(title=NULL)) 

tsne %>% ggplot(aes(x = `1`, y = `2`, color = as.factor(k6))) + geom_point()  +   ggtitle("t-SNE Plot, k=6") + theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "grey"), axis.line = element_line(colour = "grey"), strip.text = element_text(size = 16)) +  guides(color=guide_legend(title=NULL)) 

```

# PCA

```{r}
# Plot PCA
ggplot(pc_scores, aes(x = PC1, y = PC2)) +
  geom_point() +  xlab("PC1") +   ylab("PC2") 

pc_scores <- pc_scores %>% left_join(., zscored, by = "SampleID") %>% left_join(., cluster_memberships, by = "SampleID")

ggplot(pc_scores, aes(x = PC1, y = PC2, color = as.factor(dana1))) +
  geom_point() +  xlab("PC1") +   ylab("PC2") +
  ggtitle("PCA Plot, DANA") + theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "grey"), axis.line = element_line(colour = "grey"), strip.text = element_text(size = 16)) +  guides(color=guide_legend(title=NULL)) + scale_color_manual(values = c("lightpink", "deeppink", "midnightblue", "black", "lightgreen"))

ggplot(pc_scores, aes(x = PC1, y = PC2, color = as.factor(site))) +
  geom_point() +  xlab("PC1") +   ylab("PC2") +
  ggtitle("PCA Plot, site") + theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "grey"), axis.line = element_line(colour = "grey"), strip.text = element_text(size = 16)) +  guides(color=guide_legend(title=NULL))  + scale_color_manual(values = c("lightpink", "deeppink", "midnightblue"))

ggplot(pc_scores, aes(x = PC1, y = PC2, color = as.factor(sex))) +
  geom_point() +  xlab("PC1") +   ylab("PC2") +
  ggtitle("PCA Plot, sex") + theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "grey"), axis.line = element_line(colour = "grey"), strip.text = element_text(size = 16)) +  guides(color=guide_legend(title=NULL))  + scale_color_manual(values = c("lightpink", "deeppink"))

ggplot(pc_scores, aes(x = PC1, y = PC2, color = as.factor(k5.memberships))) +
  geom_point() +  xlab("PC1") +   ylab("PC2") +
  ggtitle("PCA Plot, k = 5") + theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "grey"), axis.line = element_line(colour = "grey"), strip.text = element_text(size = 16)) +  guides(color=guide_legend(title=NULL))  

ggplot(pc_scores, aes(x = PC3, y = PC4, color = as.factor(k5.memberships))) +
  geom_point() +  xlab("PC3") +   ylab("PC4") +
  ggtitle("PCA Plot, k = 5") + theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "grey"), axis.line = element_line(colour = "grey"), strip.text = element_text(size = 16)) +  guides(color=guide_legend(title=NULL))  

ggplot(pc_scores, aes(x = PC1, y = PC2, color = as.factor(k6.memberships))) +
  geom_point() +  xlab("PC1") +   ylab("PC2") +
  ggtitle("PCA Plot, k = 5") + theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "grey"), axis.line = element_line(colour = "grey"), strip.text = element_text(size = 16)) +  guides(color=guide_legend(title=NULL)) 

ggplot(pc_scores, aes(x = PC3, y = PC4, color = as.factor(k6.memberships))) +
  geom_point() +  xlab("PC3") +   ylab("PC4") +
  ggtitle("PCA Plot, k = 6") + theme(panel.background = element_blank(), panel.grid.major = element_line(colour = "grey"), axis.line = element_line(colour = "grey"), strip.text = element_text(size = 16)) +  guides(color=guide_legend(title=NULL))  

```


